[build]
base = "client/"
publish = "build/"

[[headers]]
#Define which paths this specific [[headers]] block will cover.
for = "/"
[headers.values]
Access-Control-Allow-Origin = "https://hygeia.netlify.app"